---
extlibs: '/extlibs'

swap_file: '/swap'
swap_file_size_mb: 4096

boost_dir: '{{ extlibs }}/boost'
boost_version: 'boost_1_58_0'
boost_url: 'https://storage.googleapis.com/iotivity/boost/{{ boost_version}}.zip'

expat_version: 'expat_2.1.0'
expat_url: 'https://launchpad.net/ubuntu/+archive/primary/+files'

gtest_url: 'https://github.com/google/googletest/archive'
gtest_versions:
  - 1.7.0
  - 1.8.0

tinycbor_url: 'https://github.com/intel/tinycbor/archive'
tinycbor_versions:
  - 0.2.1
  - 0.3.2
  - 0.4
  - 0.4.1
  - 0.4.2
  - 0.5.0
  - 0.5.1

sqlite_version: 'sqlite-amalgamation-3081101'
sqlite_url: 'https://www.sqlite.org/2015/{{ sqlite_version }}.zip'

android_ndk_version: 'r10e'
android_ndk_dir: '{{ extlibs }}/android/ndk'
android_ndk_url: 'http://dl.google.com/android/ndk/android-ndk-{{ android_ndk_version }}-linux-x86_64.bin'

android_sdk_version: 'r24.2'
android_sdk_dir: '{{ extlibs }}/android/sdk'
android_sdk_url: 'http://dl.google.com/android/android-sdk_{{ android_sdk_version }}-linux.tgz'

android_platform_version: '5.0.1'
android_platform_api_major_version: '21'
android_platform_api_minor_version: 'r02'
android_platform_api_version: '{{ android_platform_api_major_version }}_{{ android_platform_api_minor_version }}'
android_platform_url: 'http://dl.google.com/android/repository/android-{{ android_platform_api_version }}.zip'

android_build_tools_api_version: '4.4W'
android_build_tools_version: 'r20'
android_build_tools_expanded_version: '20.0.0'
android_build_tools_url: 'https://dl.google.com/android/repository/build-tools_{{ android_build_tools_version }}-linux.zip'

android_gradle_version: '2.2.1'
android_gradle_dir: '{{ extlibs }}/android/gradle'
android_gradle_url: 'https://services.gradle.org/distributions/gradle-{{ android_gradle_version }}-all.zip'

hippomocks_version: '5.0'
hippomocks_url: 'https://github.com/dascandy/hippomocks/archive'

rapidjson_version : '1.1.0'
rapidjson_url: 'https://github.com/miloyip/rapidjson/archive'

tizen_base_noarch:
  - autoconf-2.68-1.1.noarch.rpm
  - automake-1.11.1-1.1.noarch.rpm
  - build-2011.01.10a-1.1.noarch.rpm
  - build-compare-2009.10.14-1.6.noarch.rpm
  - cross-armv7l-platformfile-0.0.1-1.1.noarch.rpm
  - filesystem-0.1-1.1.noarch.rpm
  - perl-HTML-Tagset-3.20-1.1.noarch.rpm
  - perl-TimeDate-1.20-1.1.noarch.rpm
  - perl-URI-1.54-1.1.noarch.rpm
  - perl-libwww-perl-5.836-1.1.noarch.rpm
  - setup-0.2-1.1.noarch.rpm
  - tizen-release-2.2.0-1.1.noarch.rpm
  - tzdata-2014j-1.1.noarch.rpm


tizen_base_armv7l:
  - bash-4.1-1.6.armv7l.rpm
  - bash-x86-arm-4.1-9.1.4.armv7l.rpm
  - binutils-2.25.0-2015.01.1.8.armv7l.rpm
  - bzip2-1.0.5-1.8.armv7l.rpm
  - bzip2-libs-1.0.5-1.8.armv7l.rpm
  - bzip2-libs-x86-arm-1.0.5-9.1.4.armv7l.rpm
  - bzip2-x86-arm-1.0.5-1.4.armv7l.rpm
  - cmake-2.8.5-1.1.2.armv7l.rpm
  - cmake-x86-arm-2.8.5-1.3.armv7l.rpm
  - coreutils-6.9-1.6.armv7l.rpm
  - coreutils-x86-arm-6.9-9.1.4.armv7l.rpm
  - cpio-2.8-1.6.armv7l.rpm
  - cpp-4.9.2-2015.02.1.11.armv7l.rpm
  - cross-armv7l-binutils-accel-x86-armv7l-2.25.0-2015.01.1.3.armv7l.rpm
  - cross-armv7l-gcc-accel-x86-armv7l-4.9.2-2015.02.1.6.armv7l.rpm
  - db4-4.8.30-1.8.armv7l.rpm
  - diffutils-3.0-1.6.armv7l.rpm
  - diffutils-x86-arm-3.0-9.1.4.armv7l.rpm
  - elfutils-0.152-1.12.armv7l.rpm
  - elfutils-libelf-0.152-1.12.armv7l.rpm
  - elfutils-libelf-x86-arm-0.152-9.1.4.armv7l.rpm
  - elfutils-libs-0.152-1.12.armv7l.rpm
  - elfutils-libs-x86-arm-0.152-9.1.4.armv7l.rpm
  - elfutils-x86-arm-0.152-9.1.4.armv7l.rpm
  - expat-2.0.1-1.8.armv7l.rpm
  - expat-devel-2.0.1-1.8.armv7l.rpm
  - expat-x86-arm-2.0.1-1.4.armv7l.rpm
  - fdupes-1.40-1.5.armv7l.rpm
  - fdupes-x86-arm-1.40-9.1.4.armv7l.rpm
  - file-5.04-1.7.armv7l.rpm
  - file-x86-arm-5.04-9.1.4.armv7l.rpm
  - findutils-4.2.31-1.5.armv7l.rpm
  - findutils-x86-arm-4.2.31-9.1.4.armv7l.rpm
  - gawk-3.1.5-1.6.armv7l.rpm
  - gawk-x86-arm-3.1.5-9.1.3.armv7l.rpm
  - gcc-4.9.2-2015.02.1.11.armv7l.rpm
  - gcc-c++-4.9.2-2015.02.1.11.armv7l.rpm
  - gdbm-1.8.3-1.12.armv7l.rpm
  - gettext-runtime-0.18.3.2-1.12.armv7l.rpm
  - gettext-tools-0.18.3.2-1.12.armv7l.rpm
  - glibc-2.20-2014.11.1.10.armv7l.rpm
  - glibc-common-2.20-2014.11.1.10.armv7l.rpm
  - glibc-devel-2.20-2014.11.1.10.armv7l.rpm
  - glibc-headers-2.20-2014.11.1.10.armv7l.rpm
  - glibc-x86-arm-2.20-9.1.5.armv7l.rpm
  - grep-2.5.1a-1.5.armv7l.rpm
  - gzip-1.3.12-1.6.armv7l.rpm
  - gzip-x86-arm-1.3.12-9.1.4.armv7l.rpm
  - kernel-headers-3.4.91-1.1.armv7l.rpm
  - libacl-2.2.49-1.5.armv7l.rpm
  - libacl-x86-arm-2.2.49-9.1.4.armv7l.rpm
  - libarchive-2.8.3-1.2.armv7l.rpm
  - libarchive-x86-arm-2.8.3-1.3.armv7l.rpm
  - libasan-4.9.2-2015.02.1.11.armv7l.rpm
  - libatomic-4.9.2-2015.02.1.11.armv7l.rpm
  - libattr-2.4.44-1.8.armv7l.rpm
  - libattr-x86-arm-2.4.44-9.1.4.armv7l.rpm
  - libblkid-2.20.2-1.4.armv7l.rpm
  - libcap-2.21-1.6.armv7l.rpm
  - libcap-x86-arm-2.21-9.1.4.armv7l.rpm
  - libfile-5.04-1.7.armv7l.rpm
  - libfile-x86-arm-5.04-9.1.4.armv7l.rpm
  - libgcc-4.9.2-2015.02.1.11.armv7l.rpm
  - libgcc-x86-arm-4.9.2-9.1.4.armv7l.rpm
  - libgomp-4.9.2-2015.02.1.11.armv7l.rpm
  - libidn-1.15-1.6.armv7l.rpm
  - libidn-devel-1.15-1.6.armv7l.rpm
  - libitm-4.9.2-2015.02.1.11.armv7l.rpm
  - liblua-5.1.4-1.6.armv7l.rpm
  - liblua-x86-arm-5.1.4-9.1.3.armv7l.rpm
  - libmount-2.20.2-1.4.armv7l.rpm
  - libpcre-7.7-1.25.armv7l.rpm
  - libpython-2.7.1-1.5.armv7l.rpm
  - libpython-x86-arm-2.7.1-9.1.3.armv7l.rpm
  - libstdc++-4.9.2-2015.02.1.11.armv7l.rpm
  - libstdc++-devel-4.9.2-2015.02.1.11.armv7l.rpm
  - libstdc++-x86-arm-4.9.2-9.1.4.armv7l.rpm
  - libtool-2.2.6b-1.8.armv7l.rpm
  - libubsan-4.9.2-2015.02.1.11.armv7l.rpm
  - libuuid-2.20.2-1.4.armv7l.rpm
  - libuuid-devel-2.20.2-1.4.armv7l.rpm
  - libxml2-2.9.2-1.3.armv7l.rpm
  - libxml2-x86-arm-2.9.2-9.1.3.armv7l.rpm
  - libxslt-1.1.28-1.2.armv7l.rpm
  - m4-1.4.14-1.5.armv7l.rpm
  - m4-x86-arm-1.4.14-9.1.4.armv7l.rpm
  - make-3.82-154.1.6.armv7l.rpm
  - make-x86-arm-3.82-9.1.3.armv7l.rpm
  - minizip-1.2.8-1.8.armv7l.rpm
  - ncurses-5.7-1.8.armv7l.rpm
  - ncurses-base-5.7-1.8.armv7l.rpm
  - ncurses-libs-5.7-1.8.armv7l.rpm
  - ncurses-libs-x86-arm-5.7-9.1.3.armv7l.rpm
  - net-tools-1.60-2.6.armv7l.rpm
  - nspr-4.9-1.9.armv7l.rpm
  - nspr-x86-arm-4.9-9.1.5.armv7l.rpm
  - nss-3.12.9-1.17.armv7l.rpm
  - nss-softokn-freebl-3.12.9-1.17.armv7l.rpm
  - nss-softokn-freebl-x86-arm-3.12.9-9.1.5.armv7l.rpm
  - nss-sysinit-3.12.9-1.17.armv7l.rpm
  - nss-x86-arm-3.12.9-9.1.5.armv7l.rpm
  - openssl-1.0.1p-1.5.armv7l.rpm
  - openssl-devel-1.0.1p-1.5.armv7l.rpm
  - openssl-x86-arm-1.0.1p-9.1.3.armv7l.rpm
  - pam-1.1.5-1.5.armv7l.rpm
  - patch-2.6-1.6.armv7l.rpm
  - patch-x86-arm-2.6-9.1.4.armv7l.rpm
  - patchelf-0.5.svn20809-1.5.armv7l.rpm
  - pcre-7.7-1.25.armv7l.rpm
  - perl-5.12.1-1.25.armv7l.rpm
  - perl-Compress-Raw-Zlib-2.008-1.25.armv7l.rpm
  - perl-Compress-Zlib-2.008-1.25.armv7l.rpm
  - perl-HTML-Parser-3.65-1.5.armv7l.rpm
  - perl-HTML-Parser-x86-arm-3.65-9.1.3.armv7l.rpm
  - perl-IO-Compress-Base-2.008-1.25.armv7l.rpm
  - perl-IO-Compress-Zlib-2.008-1.25.armv7l.rpm
  - perl-Module-Pluggable-3.60-1.25.armv7l.rpm
  - perl-Pod-Escapes-1.04-1.25.armv7l.rpm
  - perl-Pod-Simple-3.07-1.25.armv7l.rpm
  - perl-XML-Parser-2.36-1.6.armv7l.rpm
  - perl-XML-Parser-x86-arm-2.36-9.1.3.armv7l.rpm
  - perl-libs-5.12.1-1.25.armv7l.rpm
  - perl-libs-x86-arm-5.12.1-9.1.5.armv7l.rpm
  - perl-x86-arm-5.12.1-9.1.5.armv7l.rpm
  - pkg-config-0.25-2.6.armv7l.rpm
  - pkg-config-x86-arm-0.25-9.1.4.armv7l.rpm
  - popt-1.16-1.8.armv7l.rpm
  - popt-x86-arm-1.16-9.1.4.armv7l.rpm
  - psmisc-22.20-1.6.armv7l.rpm
  - python-2.7.1-1.3.armv7l.rpm
  - python-base-2.7.1-1.5.armv7l.rpm
  - python-base-x86-arm-2.7.1-9.1.3.armv7l.rpm
  - python-x86-arm-2.7.1-9.1.3.armv7l.rpm
  - python-xml-2.7.1-1.5.armv7l.rpm
  - python-xml-x86-arm-2.7.1-9.1.3.armv7l.rpm
  - qemu-linux-user-x86-arm-2.2.0-4.1.1.armv7l.rpm
  - readline-5.2-1.6.armv7l.rpm
  - rpm-4.9.1-4.3.1.10.armv7l.rpm
  - rpm-build-4.9.1-4.3.1.10.armv7l.rpm
  - rpm-build-x86-arm-4.9.1-9.1.4.armv7l.rpm
  - rpm-libs-4.9.1-4.3.1.10.armv7l.rpm
  - rpm-libs-x86-arm-4.9.1-9.1.4.armv7l.rpm
  - rpm-x86-arm-4.9.1-9.1.4.armv7l.rpm
  - ruby-1.9.2-1.6.armv7l.rpm
  - ruby-x86-arm-1.9.2-9.1.4.armv7l.rpm
  - sed-4.1.5-1.5.armv7l.rpm
  - sed-x86-arm-4.1.5-9.1.4.armv7l.rpm
  - smack-1.0+s14-1.8.armv7l.rpm
  - smack-utils-1.0+s14-1.8.armv7l.rpm
  - sqlite-3.8.10.2-1.8.armv7l.rpm
  - sqlite-devel-3.8.10.2-1.8.armv7l.rpm
  - sqlite-x86-arm-3.8.10.2-9.1.3.armv7l.rpm
  - tar-1.17-1.6.armv7l.rpm
  - tar-x86-arm-1.17-9.1.4.armv7l.rpm
  - tizen-accelerator-1.0.1-1.1.armv7l.rpm
  - unzip-6.0-1.12.armv7l.rpm
  - util-linux-2.20.2-1.4.armv7l.rpm
  - xz-5.0.3-1.8.armv7l.rpm
  - xz-libs-5.0.3-1.8.armv7l.rpm
  - xz-libs-x86-arm-5.0.3-9.1.4.armv7l.rpm
  - xz-lzma-compat-5.0.3-1.8.armv7l.rpm
  - zlib-1.2.8-1.8.armv7l.rpm
  - zlib-x86-arm-1.2.8-9.1.4.armv7l.rpm

tizen_mobile_noarch:
  - gio-branding-upstream-2.44.1-2.1.noarch.rpm
  - libX11-common-1.6.2-1.1.noarch.rpm

tizen_mobile_armv7l:
  - bluetooth-frwk-0.2.149-3.1.armv7l.rpm
  - bluetooth-tools-0.2.45-1.1.armv7l.rpm
  - boost-1.51.0-1.1.armv7l.rpm
  - boost-chrono-1.51.0-1.1.armv7l.rpm
  - boost-date-time-1.51.0-1.1.armv7l.rpm
  - boost-devel-1.51.0-1.1.armv7l.rpm
  - boost-filesystem-1.51.0-1.1.armv7l.rpm
  - boost-iostreams-1.51.0-1.1.armv7l.rpm
  - boost-program-options-1.51.0-1.1.armv7l.rpm
  - boost-random-1.51.0-1.1.armv7l.rpm
  - boost-regex-1.51.0-1.1.armv7l.rpm
  - boost-serialization-1.51.0-1.1.armv7l.rpm
  - boost-system-1.51.0-1.1.armv7l.rpm
  - boost-test-1.51.0-1.1.armv7l.rpm
  - boost-thread-1.51.0-1.1.armv7l.rpm
  - bundle-0.1.36-1.1.armv7l.rpm
  - c-ares-1.10.0_5-1.1.armv7l.rpm
  - ca-certificates-0.0.1-1.1.armv7l.rpm
  - capi-base-common-0.2.2-1.1.armv7l.rpm
  - capi-base-common-devel-0.2.2-1.1.armv7l.rpm
  - capi-network-bluetooth-0.1.53-3.1.armv7l.rpm
  - capi-network-bluetooth-devel-0.1.53-3.1.armv7l.rpm
  - capi-network-connection-1.0.72-1.3.armv7l.rpm
  - capi-network-connection-devel-1.0.72-1.3.armv7l.rpm
  - capi-system-info-0.2.0-1.2.armv7l.rpm
  - cert-svc-1.0.2-1.1.armv7l.rpm
  - chrpath-0.13-1.1.armv7l.rpm
  - coregl-4.0-1.1.armv7l.rpm
  - dbus-1.8.16-2.1.armv7l.rpm
  - dbus-glib-0.100-1.1.armv7l.rpm
  - dbus-libs-1.8.16-2.1.armv7l.rpm
  - ecore-1.13.26-3.1.armv7l.rpm
  - ector-1.13.26-3.1.armv7l.rpm
  - edbus-1.6.0+svn.76526slp2+build11-1.2.armv7l.rpm
  - edje-1.13.26-3.1.armv7l.rpm
  - eet-1.13.26-3.1.armv7l.rpm
  - eeze-1.13.26-3.1.armv7l.rpm
  - efl-1.13.26-3.1.armv7l.rpm
  - efreet-1.13.26-3.1.armv7l.rpm
  - eina-1.13.26-3.1.armv7l.rpm
  - eio-1.13.26-3.1.armv7l.rpm
  - eldbus-1.13.26-3.1.armv7l.rpm
  - elementary-1.13.33-1.2.armv7l.rpm
  - embryo-1.13.26-3.1.armv7l.rpm
  - emotion-1.13.26-3.1.armv7l.rpm
  - eo-1.13.26-3.1.armv7l.rpm
  - ethumb-1.13.26-3.1.armv7l.rpm
  - evas-1.13.26-3.1.armv7l.rpm
  - eventsystem-0.0.1-1.1.armv7l.rpm
  - fontconfig-2.11.92-1.1.armv7l.rpm
  - freetype-2.5.5-1.1.armv7l.rpm
  - fribidi-0.19.6-1.1.armv7l.rpm
  - giflib-4.1.6-1.1.armv7l.rpm
  - glib2-devel-2.44.1-2.1.armv7l.rpm
  - glib2-tools-2.44.1-2.1.armv7l.rpm
  - harfbuzz-0.9.40-1.1.armv7l.rpm
  - iniparser-3.1-1.1.armv7l.rpm
  - key-manager-0.1.13-1.1.armv7l.rpm
  - kmod-libs-15-1.1.armv7l.rpm
  - libX11-1.6.2-1.1.armv7l.rpm
  - libXau-1.0.8-1.1.armv7l.rpm
  - libXcomposite-0.4.4-1.1.armv7l.rpm
  - libXcursor-1.1.14-1.1.armv7l.rpm
  - libXdamage-1.1.4-1.1.armv7l.rpm
  - libXext-1.3.2-1.1.armv7l.rpm
  - libXfixes-5.0.1-1.1.armv7l.rpm
  - libXgesture-0.1.1-1.1.armv7l.rpm
  - libXi-1.7.3-1.1.armv7l.rpm
  - libXinerama-1.1.3-1.1.armv7l.rpm
  - libXrandr-1.4.2-1.1.armv7l.rpm
  - libXrender-0.9.8-1.1.armv7l.rpm
  - libXtst-1.2.4-1.1.armv7l.rpm
  - libXv-1.0.10-1.1.armv7l.rpm
  - libcurl-7.40.1_6-1.1.armv7l.rpm
  - libcurl-devel-7.40.1_6-1.1.armv7l.rpm
  - libdlog-0.4.1-1.1.armv7l.rpm
  - libdlog-devel-0.4.1-1.1.armv7l.rpm
  - libdri2-0.2.1-1.1.armv7l.rpm
  - libdrm2-2.4.35-1.1.armv7l.rpm
  - libffi-3.1-1.1.armv7l.rpm
  - libgio-2.44.1-2.1.armv7l.rpm
  - libglib-2.44.1-2.1.armv7l.rpm
  - libgmodule-2.44.1-2.1.armv7l.rpm
  - libgobject-2.44.1-2.1.armv7l.rpm
  - libgthread-2.44.1-2.1.armv7l.rpm
  - libicu-51-1.1.armv7l.rpm
  - libiri-1.7-1.1.armv7l.rpm
  - libjpeg-turbo-1.2.0-1.1.armv7l.rpm
  - libkey-manager-client-0.1.13-1.1.armv7l.rpm
  - libkey-manager-common-0.1.13-1.1.armv7l.rpm
  - libleveldb-1.1_17-1.1.armv7l.rpm
  - libnet-client-1.1.42-1.2.armv7l.rpm
  - libpng-1.2.50-1.1.armv7l.rpm
  - libprivilege-control-0.0.93-1.1.armv7l.rpm
  - libresourced-0.2.86-1.4.armv7l.rpm
  - librua-0.1.8-1.1.armv7l.rpm
  - libsecurity-server-client-0.0.132-1.1.armv7l.rpm
  - libslp-db-util-0.1.8-1.1.armv7l.rpm
  - libslp-utilx-0.5.4-1.1.armv7l.rpm
  - libss-client-0.12.13-1.1.armv7l.rpm
  - libtbm-1.1.8-1.1.armv7l.rpm
  - libtiff-4.0.2-1.1.armv7l.rpm
  - libunwind-1.1-1.1.armv7l.rpm
  - libwayland-client-1.7.0-1.1.armv7l.rpm
  - libxcb-1.10.0-1.1.armv7l.rpm
  - nghttp2-0.7.3-1.1.armv7l.rpm
  - pkgmgr-0.3.37-1.2.armv7l.rpm
  - pkgmgr-client-0.3.37-1.2.armv7l.rpm
  - pkgmgr-info-0.0.230-1.2.armv7l.rpm
  - pkgmgr-info-parser-0.0.230-1.2.armv7l.rpm
  - pkgmgr-installer-0.3.37-1.2.armv7l.rpm
  - resourced-0.2.86-1.4.armv7l.rpm
  - security-server-0.0.132-1.1.armv7l.rpm
  - smack-privilege-config-1.0.8-2.1.armv7l.rpm
  - ss-server-0.12.13-1.1.armv7l.rpm
  - sys-assert-0.3.2-1.1.armv7l.rpm
  - syspopup-0.0.135-1.4.armv7l.rpm
  - syspopup-caller-0.0.135-1.4.armv7l.rpm
  - systemd-216-1.3.armv7l.rpm
  - systemd-libs-216-1.3.armv7l.rpm
  - tizen-security-policy-1.2.2.1-1.1.armv7l.rpm
  - ttrace-1.0.0-1.1.armv7l.rpm
  - vasum-0.3.1-1.1.armv7l.rpm
  - vconf-0.2.84-2.1.armv7l.rpm
  - xdgmime-0.0.12-1.1.armv7l.rpm
  - xmlsec1-1.2.14-1.1.armv7l.rpm
  - xmlsec1-openssl-1.2.14-1.1.armv7l.rpm

